apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
spec:
  replicas: 1
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: docker.io/postgres:14-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-configmap
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              cpu: 500m
              memory: '1Gi'
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-pvc
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres-service