apiVersion: v1
kind: Service
metadata:
  name: synapse-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8008
    protocol: TCP
    targetPort: 8008
    nodePort: 30080
  selector:
    app: synapse
