apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-synapse-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: db-synapse
      labels:
        app: db-synapse
    spec:
      containers:
        - name: db-synapse-container
          image: docker.io/postgres:14-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-configmap
  selector:
    matchLabels:
      app: db-synapse