apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-synapse-ingress
  annotations:
    # Define o tamanho máximo do arquivo que pode ser enviado.
    # "max_upload_size" também precisa ser ajustado no homeserver.yaml.
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-synapse
  rules:
  - host: matrix.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: synapse-service
            port:
              number: 8008
  tls:
  - hosts:
    - matrix.example.com
    secretName: example.com